controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

diff_drive_controller:
  ros__parameters:
    left_wheel_names: ["base_link_Revolute-6"]
    right_wheel_names: ["base_link_Revolute-5"]

    wheel_separation: 0.16
    wheel_radius: 0.02

    use_stamped_vel: false

    # Publish rate for wheel odometry
    publish_rate: 50.0

    # Wheel separation and radius multipliers
    wheel_separation_multiplier: 1.0
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0

    # Velocity and acceleration limits
    linear:
      x:
        has_velocity_limits: true
        max_velocity: 0.5 # m/s
        has_acceleration_limits: true
        max_acceleration: 1.0 # m/s^2
    angular:
      z:
        has_velocity_limits: true
        max_velocity: 1.0 # rad/s
        has_acceleration_limits: true
        max_acceleration: 2.0 # rad/s^2

    # Feedback gains for velocity control
    pose_covariance_diagonal: [0.001, 0.001, 0.0, 0.0, 0.0, 0.01]
    twist_covariance_diagonal: [0.001, 0.0, 0.0, 0.0, 0.0, 0.01]

    # Controller state
    open_loop: false
    enable_odom_tf: true

    # Base frame
    base_frame_id: base_link
    odom_frame_id: odom

    # Hardware interface types
    position_feedback: false
    velocity_feedback: true
    publish_limited_velocity: true
    publish_cmd: true

    # Velocity command timeout
    cmd_vel_timeout: 0.5 # seconds